# Generated by Django 3.0.5 on 2020-04-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='attended',
            new_name='attending',
        ),
    ]
