# Generated by Django 3.0.5 on 2020-04-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200421_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'ordering': ('service', 'id')},
        ),
        migrations.AddField(
            model_name='queue',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
