# Generated by Django 3.0.5 on 2020-04-21 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200421_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='core.Service'),
        ),
    ]
