# Generated by Django 3.0.5 on 2020-04-21 20:02

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200421_1330'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='queue',
            managers=[
                ('enqueue', django.db.models.manager.Manager()),
            ],
        ),
    ]
